dist: bionic
sudo: require
language: cpp
compiler: clang
addons:
  snaps:
    - name: cmake
      confinement: classic
      channel: 3.14/stable
  apt:
    update: true
    packages:
      - make
script:
  - clang --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make
