dist: bionic
sudo: require
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - make
script:
  - clang --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - make
